# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: code_analysis_output.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'code_analysis_output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ode_analysis_output.proto\x12\x11\x63ofix.analysis.v1\"\x89\x01\n\tCodeIssue\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1b\n\x13learning_directions\x18\x05 \x03(\t\x12\x0f\n\x07\x64\x61taset\x18\x06 \x01(\t\x12\r\n\x05guide\x18\x07 \x01(\t\"I\n\x13\x41nalyzeCodeResponse\x12,\n\x06issues\x18\x01 \x03(\x0b\x32\x1c.cofix.analysis.v1.CodeIssueJ\x04\x08\x02\x10\x03\x42\"\n\x1ekr.jongyeol.cofix.grpc.analyzeP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_proto.code_analysis_output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036kr.jongyeol.cofix.grpc.analyzeP\001'
  _globals['_CODEISSUE']._serialized_start=50
  _globals['_CODEISSUE']._serialized_end=187
  _globals['_ANALYZECODERESPONSE']._serialized_start=189
  _globals['_ANALYZECODERESPONSE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
