# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: code_analysis_input.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'code_analysis_input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from generated_proto import code_analysis_output_pb2 as code__analysis__output__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ode_analysis_input.proto\x12\x11\x63ofix.analysis.v1\x1a\x1a\x63ode_analysis_output.proto\"g\n\x0bRecentIssue\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1b\n\x13learning_directions\x18\x03 \x03(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\r\n\x05guide\x18\x05 \x01(\t\"H\n\x0fLearningContext\x12\x35\n\rrecent_issues\x18\x01 \x03(\x0b\x32\x1e.cofix.analysis.v1.RecentIssue\"u\n\x12\x41nalyzeCodeRequest\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\r\n\x05patch\x18\x03 \x01(\t\x12<\n\x10learning_context\x18\x04 \x01(\x0b\x32\".cofix.analysis.v1.LearningContextJ\x04\x08\x01\x10\x02\x32s\n\x13\x43odeAnalysisService\x12\\\n\x0b\x41nalyzeCode\x12%.cofix.analysis.v1.AnalyzeCodeRequest\x1a&.cofix.analysis.v1.AnalyzeCodeResponseB<\n\x1ekr.jongyeol.cofix.grpc.analyzeB\x18\x43odeAnalysisServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_proto.code_analysis_input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036kr.jongyeol.cofix.grpc.analyzeB\030CodeAnalysisServiceProtoP\001'
  _globals['_RECENTISSUE']._serialized_start=76
  _globals['_RECENTISSUE']._serialized_end=179
  _globals['_LEARNINGCONTEXT']._serialized_start=181
  _globals['_LEARNINGCONTEXT']._serialized_end=253
  _globals['_ANALYZECODEREQUEST']._serialized_start=255
  _globals['_ANALYZECODEREQUEST']._serialized_end=372
  _globals['_CODEANALYSISSERVICE']._serialized_start=374
  _globals['_CODEANALYSISSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
