# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from generated_proto import issue_quiz_input_pb2 as proto_dot_issue__quiz__input__pb2
from generated_proto import issue_quiz_output_pb2 as proto_dot_issue__quiz__output__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/issue_quiz_input_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IssueQuizServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateIssueQuiz = channel.unary_unary(
                '/cofix.quiz.v1.IssueQuizService/GenerateIssueQuiz',
                request_serializer=proto_dot_issue__quiz__input__pb2.GenerateIssueQuizRequest.SerializeToString,
                response_deserializer=proto_dot_issue__quiz__output__pb2.GenerateIssueQuizResponse.FromString,
                _registered_method=True)


class IssueQuizServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateIssueQuiz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IssueQuizServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateIssueQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateIssueQuiz,
                    request_deserializer=proto_dot_issue__quiz__input__pb2.GenerateIssueQuizRequest.FromString,
                    response_serializer=proto_dot_issue__quiz__output__pb2.GenerateIssueQuizResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cofix.quiz.v1.IssueQuizService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cofix.quiz.v1.IssueQuizService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IssueQuizService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateIssueQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cofix.quiz.v1.IssueQuizService/GenerateIssueQuiz',
            proto_dot_issue__quiz__input__pb2.GenerateIssueQuizRequest.SerializeToString,
            proto_dot_issue__quiz__output__pb2.GenerateIssueQuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
