# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: issue_quiz_input.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'issue_quiz_input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from generated_proto import issue_quiz_output_pb2 as issue__quiz__output__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16issue_quiz_input.proto\x12\rcofix.quiz.v1\x1a\x17issue_quiz_output.proto\"g\n\x0bRecentIssue\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1b\n\x13learning_directions\x18\x03 \x03(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\r\n\x05guide\x18\x05 \x01(\t\"u\n\x18GenerateIssueQuizRequest\x12\x16\n\x0eselected_level\x18\x01 \x01(\t\x12\x15\n\rproblem_count\x18\x02 \x01(\x05\x12*\n\x06issues\x18\x03 \x03(\x0b\x32\x1a.cofix.quiz.v1.RecentIssue2z\n\x10IssueQuizService\x12\x66\n\x11GenerateIssueQuiz\x12\'.cofix.quiz.v1.GenerateIssueQuizRequest\x1a(.cofix.quiz.v1.GenerateIssueQuizResponseB6\n\x1bkr.jongyeol.cofix.grpc.quizB\x15IssueQuizServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_proto.issue_quiz_input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033kr.jongyeol.cofix.grpc.quizB\025IssueQuizServiceProtoP\001'
  _globals['_RECENTISSUE']._serialized_start=66
  _globals['_RECENTISSUE']._serialized_end=169
  _globals['_GENERATEISSUEQUIZREQUEST']._serialized_start=171
  _globals['_GENERATEISSUEQUIZREQUEST']._serialized_end=288
  _globals['_ISSUEQUIZSERVICE']._serialized_start=290
  _globals['_ISSUEQUIZSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
