# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: issue_quiz_output.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'issue_quiz_output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17issue_quiz_output.proto\x12\rcofix.quiz.v1\"&\n\nQuizChoice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"2\n\rQuizCodeBlock\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xb6\x01\n\x0bQuizProblem\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x35\n\ncode_block\x18\x02 \x01(\x0b\x32\x1c.cofix.quiz.v1.QuizCodeBlockH\x00\x88\x01\x01\x12*\n\x07\x63hoices\x18\x03 \x03(\x0b\x32\x19.cofix.quiz.v1.QuizChoice\x12\x0e\n\x06\x61nswer\x18\x04 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x05 \x01(\tB\r\n\x0b_code_block\"I\n\x19GenerateIssueQuizResponse\x12,\n\x08problems\x18\x01 \x03(\x0b\x32\x1a.cofix.quiz.v1.QuizProblemB\x1f\n\x1bkr.jongyeol.cofix.grpc.quizP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_proto.issue_quiz_output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033kr.jongyeol.cofix.grpc.quizP\001'
  _globals['_QUIZCHOICE']._serialized_start=42
  _globals['_QUIZCHOICE']._serialized_end=80
  _globals['_QUIZCODEBLOCK']._serialized_start=82
  _globals['_QUIZCODEBLOCK']._serialized_end=132
  _globals['_QUIZPROBLEM']._serialized_start=135
  _globals['_QUIZPROBLEM']._serialized_end=317
  _globals['_GENERATEISSUEQUIZRESPONSE']._serialized_start=319
  _globals['_GENERATEISSUEQUIZRESPONSE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
