# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: learning_chat_output.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'learning_chat_output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alearning_chat_output.proto\x12\x10\x63ofix.chatbot.v1\"\x81\x01\n\x0c\x43hatResponse\x12\x12\n\x05title\x18\x01 \x01(\tH\x00\x88\x01\x01\x12!\n\x14\x63onversation_summary\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\x0fmarkdown_answer\x18\x03 \x01(\tB\x08\n\x06_titleB\x17\n\x15_conversation_summaryB\x1f\n\x1bkr.jongyeol.cofix.grpc.chatP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_proto.learning_chat_output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033kr.jongyeol.cofix.grpc.chatP\001'
  _globals['_CHATRESPONSE']._serialized_start=49
  _globals['_CHATRESPONSE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
