# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/code_analysis_input.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/code_analysis_input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import code_analysis_output_pb2 as proto_dot_code__analysis__output__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/code_analysis_input.proto\x12\x11\x63ofix.analysis.v1\x1a proto/code_analysis_output.proto\"g\n\x0bRecentIssue\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1b\n\x13learning_directions\x18\x03 \x03(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\r\n\x05guide\x18\x05 \x01(\t\"H\n\x0fLearningContext\x12\x35\n\rrecent_issues\x18\x01 \x03(\x0b\x32\x1e.cofix.analysis.v1.RecentIssue\"f\n\x12\x41nalyzeCodeRequest\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12<\n\x10learning_context\x18\x03 \x01(\x0b\x32\".cofix.analysis.v1.LearningContextJ\x04\x08\x01\x10\x02\x32s\n\x13\x43odeAnalysisService\x12\\\n\x0b\x41nalyzeCode\x12%.cofix.analysis.v1.AnalyzeCodeRequest\x1a&.cofix.analysis.v1.AnalyzeCodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.code_analysis_input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECENTISSUE']._serialized_start=88
  _globals['_RECENTISSUE']._serialized_end=191
  _globals['_LEARNINGCONTEXT']._serialized_start=193
  _globals['_LEARNINGCONTEXT']._serialized_end=265
  _globals['_ANALYZECODEREQUEST']._serialized_start=267
  _globals['_ANALYZECODEREQUEST']._serialized_end=369
  _globals['_CODEANALYSISSERVICE']._serialized_start=371
  _globals['_CODEANALYSISSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
