# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/issue_quiz_output.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/issue_quiz_output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/issue_quiz_output.proto\x12\rcofix.quiz.v1\"&\n\nQuizChoice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"2\n\rQuizCodeBlock\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xb6\x01\n\x0bQuizProblem\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x35\n\ncode_block\x18\x02 \x01(\x0b\x32\x1c.cofix.quiz.v1.QuizCodeBlockH\x00\x88\x01\x01\x12*\n\x07\x63hoices\x18\x03 \x03(\x0b\x32\x19.cofix.quiz.v1.QuizChoice\x12\x0e\n\x06\x61nswer\x18\x04 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x05 \x01(\tB\r\n\x0b_code_block\"I\n\x19GenerateIssueQuizResponse\x12,\n\x08problems\x18\x01 \x03(\x0b\x32\x1a.cofix.quiz.v1.QuizProblemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.issue_quiz_output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUIZCHOICE']._serialized_start=48
  _globals['_QUIZCHOICE']._serialized_end=86
  _globals['_QUIZCODEBLOCK']._serialized_start=88
  _globals['_QUIZCODEBLOCK']._serialized_end=138
  _globals['_QUIZPROBLEM']._serialized_start=141
  _globals['_QUIZPROBLEM']._serialized_end=323
  _globals['_GENERATEISSUEQUIZRESPONSE']._serialized_start=325
  _globals['_GENERATEISSUEQUIZRESPONSE']._serialized_end=398
# @@protoc_insertion_point(module_scope)
