name: CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/2Team/cofix-ai

    steps:
      - name: Setup Git Safe Directory
        run: git config --global --add safe.directory /home/2Team/cofix-ai
    
      - name: Checkout code
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Install Python dependencies
        run: /home/2Team/cofix-ai/.venv/bin/pip install -r /home/2Team/cofix-ai/requirements.txt

      - name: Restart Cofix AI Service
        run: sudo systemctl restart cofix-ai

      - name: Check Cofix AI Service Status
        run: sudo systemctl status cofix-ai
